Updated colleagues

diff --git a/bin/colleagues b/bin/colleagues
--- a/bin/colleagues
+++ b/bin/colleagues
@@ -15,38 +15,24 @@ if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
 	exit 1
 fi
 
-set +e
-SSH_LDAP_HELPER="$(command -v 'ssh-ldap-helper' 2>/dev/null)"
-set -e
-SSH_LDAP_HELPER="${SSH_LDAP_HELPER:-/usr/libexec/openssh/ssh-ldap-helper}"
+if [[ -e /usr/libexec/openssh/get_public_keys_from_ldap.bash ]]; then
+	SSH_LDAP_HELPER='/usr/libexec/openssh/get_public_keys_from_ldap.bash'
+else 
+	set +e
+	SSH_LDAP_HELPER="$(command -v 'ssh-ldap-helper' 2>/dev/null)"
+	set -e
+	SSH_LDAP_HELPER="${SSH_LDAP_HELPER:-/usr/libexec/openssh/ssh-ldap-helper}"
+fi
 if [[ ! -x "${SSH_LDAP_HELPER:-}" ]]; then
 	echo "WARN: Cannot find ssh-ldap-helper, which is required to determine if users are (in)active."
 fi
 
 #
-# These are currently hard-coded values.
-# The LDAP connection details can be fetched from the ldap_config_file,
-# but there is no easy way to get the specifics of the LDAP schema from the ldap_config_file :(
+# The LDAP connection details can be fetched from a custom ldap_config_file,
+# which allows us to loop over multiple LDAP domains.
 #
-declare ldap_config_file='/etc/ssh/ldap.conf'
-#
-# For eDirectory.
-#
-declare ldap_group_object_class='groupofnames'
-declare ldap_group_owner_attr='ruggroupOwnerValue'
-declare ldap_group_datamanager_attr='ruggroupDataManagerValue'
-declare ldap_user_object_class='person'
-declare ldap_user_expiration_attr='loginexpirationtime'
-declare ldap_user_expiration_regex='^'"${ldap_user_expiration_attr}"': ([0-9]{4})([0-9]{2})([0-9]{2}).+Z$'
-#
-# For OpenLDAP.
-#
-#declare ldap_group_object_class='posixGroup'
-#declare ldap_group_owner_attr='groupOwnerUid'
-#declare ldap_group_datamanager_attr='groupDataManager'
-#declare ldap_user_object_class='inetOrgPerson'
-#declare ldap_user_expiration_attr='loginexpirationtime'
-#declare ldap_user_expiration_regex='^'"${ldap_user_expiration_attr}"': ([0-9]{4})([0-9]{2})([0-9]{2}).+Z$'
+declare ldap_config_file='/etc/openldap/readonly-ldapsearch-credentials.bash'
+declare ldap_user_expiration_regex='^([0-9]{4})([0-9]{2})([0-9]{2}).+Z$'
 
 #
 ##
@@ -90,27 +76,38 @@ function _GetLoginExpirationTimes() {
 	fi
 	local _user
 	for _user in "${!users[@]}"; do
+		if [[ "${plain_text}" -eq 0 ]]; then
+			printf '%s' '.' # Process indicator.
+		fi
 		if [[ "${users["${_user}"]}" == 'NA' ]]; then
 			local _login_expiration_time='9999-99-99'
 			local _query_result
 			local _line
-			_query_result=$(ldapsearch -LLL -o ldif-wrap=no \
-					-H "${LDAP_HOST}" \
-					-D "${LDAP_USER}" \
-					-w "${LDAP_PASS}" \
-					-b "${LDAP_SEARCH_BASE}" \
-					"(&(ObjectClass=${ldap_user_object_class})(cn:dn:=${_user}))" \
-					"${ldap_user_expiration_attr}"
+			local _ldap
+			for _ldap in "${domain_names[@]}"; do
+				local _uri="${domain_configs[${_ldap}_uri]}"
+				local _search_base="${domain_configs[${_ldap}_search_base]}"
+				local _bind_dn="${domain_configs[${_ldap}_bind_dn]}"
+				local _bind_pw="${domain_configs[${_ldap}_bind_pw]}"
+				local _user_object_class="${domain_configs[${_ldap}_user_object_class]}"
+				local _user_expiration_date="${domain_configs[${_ldap}_user_expiration_date]}"
+				_query_result=$(ldapsearch -LLL -o ldif-wrap=no \
+						-H "${_uri}" \
+						-D "${_bind_dn}" \
+						-w "${_bind_pw}" \
+						-b "${_search_base}" \
+						"(&(ObjectClass=${_user_object_class})(cn:dn:=${_user}))" \
+						"${_user_expiration_date}" \
+					| (grep "${_user_expiration_date}" || true) \
+					| sed "s/${_user_expiration_date}: //"
 				)
-			while read -r _line; do
-				if [[ "${_line}" =~ ${ldap_user_expiration_regex} ]]; then
-					_login_expiration_time="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}-${BASH_REMATCH[3]}"
-				fi
-			done < <( printf '%s\n' "${_query_result}")
-			users["${_user}"]="${_login_expiration_time}"
-			if [[ "${plain_text}" -eq 0 ]]; then
-				printf '%s' '.' # Process indicator.
-			fi
+				while read -r _line; do
+					if [[ "${_line}" =~ ${ldap_user_expiration_regex} ]]; then
+						users["${_user}"]="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}-${BASH_REMATCH[3]}"
+						continue 3
+					fi
+				done <<< "${_query_result}"
+			done
 		fi
 	done
 	if [[ "${plain_text}" -eq 0 ]]; then
@@ -179,17 +176,21 @@ function _PrintGroupInfo() {
 function _PrintUserInfo() {
 	local _user="${1}"
 	local _format="${2}"
-	local _login_expiration_time="${users["${_user}"]}"
+	local _login_expiration_time="${users["${_user}"]:-NA}"
 	local _gecos
 	local _getent_result
-	getent_result="$(getent passwd "${_user}" | cut -d ':' -s -f 1,5)"
-	IFS=':' read -r -a _user_info <<< "${getent_result}"
-	if [[ "${_login_expiration_time}" == '9999-99-99' || "${_login_expiration_time}" == 'NA' ]]; then
-		_login_expiration_time='Never'
-	fi
-	if [[ "${#_user_info[@]:0}" -ge 1 ]]; then
+	if [[ ${_user} == 'MIA' || ${_user} == 'NA' ]]; then
+		_user='MIA'
+		if [[ "${plain_text}" -eq 1 ]]; then
+			_gecos='Missing In Action.'
+		else
+			_gecos='\e[2mMissing In Action.\e[22m'
+		fi
+	elif getent passwd "${_user}" | grep -q "."; then
+		getent_result="$(getent passwd "${_user}" | cut -d ':' -s -f 1,5)"
+		IFS=':' read -r -a _user_info <<< "${getent_result}"
 		local _public_key
-		_public_key="$(${SSH_LDAP_HELPER} -s "${_user}")"
+		_public_key="$(${SSH_LDAP_HELPER} "${_user}" 2>/dev/null)"
 		if [[ -n "${_public_key}" ]]; then
 			_gecos="${_user_info[1]:-NA}"
 		else
@@ -200,20 +201,14 @@ function _PrintUserInfo() {
 			fi
 		fi
 	else
-		if [[ ${_user} == 'MIA' || ${_user} == 'NA' ]]; then
-			_user='MIA'
-			if [[ "${plain_text}" -eq 1 ]]; then
-				_gecos='Missing In Action.'
-			else
-				_gecos='\e[2mMissing In Action.\e[22m'
-			fi
+		if [[ "${plain_text}" -eq 1 ]]; then
+			_gecos='No details available (Not entitled to use this server/machine).'
 		else
-			if [[ "${plain_text}" -eq 1 ]]; then
-				_gecos='No details available (Not entitled to use this server/machine).'
-			else
-				_gecos='\e[2mNo details available (Not entitled to use this server/machine).\e[22m'
-			fi
+			_gecos='\e[2mNo details available (Not entitled to use this server/machine).\e[22m'
 		fi
+	fi
+	if [[ "${_login_expiration_time}" == '9999-99-99' || "${_login_expiration_time}" == 'NA' ]]; then
+		_login_expiration_time='Never'
 	fi
 	printf "${_format}" "${_user}" "${_login_expiration_time}" "${_gecos}";
 }
@@ -311,10 +306,11 @@ fi
 #
 # Parse LDAP config file.
 #
-LDAP_HOST="$(awk '$1 == "uri" {print $2}' "${ldap_config_file}")"
-LDAP_USER="$(awk '$1 == "binddn" {print $2}' "${ldap_config_file}")"
-LDAP_PASS="$(awk '$1 == "bindpw" {print $2}' "${ldap_config_file}")"
-LDAP_SEARCH_BASE="$(awk '$1 == "base" {print $2}' "${ldap_config_file}")"
+if [[ -e  "${ldap_config_file}" ]]; then
+	source "${ldap_config_file}"
+else
+	echo "FATAL: ${ldap_config_file} is required for this version of ${memyselfandi}, but does not exist on this machine."
+fi
 
 #
 # List owners, data managers and members per group.
@@ -351,21 +347,6 @@ for group in "${groups[@]}"; do
 		if [[ -n "${query_result:-}" ]]; then
 			readarray -t owners <<< "${query_result}"
 		fi
-	else
-		query_result=$(ldapsearch -LLL -o ldif-wrap=no \
-				-H "${LDAP_HOST}" \
-				-D "${LDAP_USER}" \
-				-w "${LDAP_PASS}" \
-				-b "${LDAP_SEARCH_BASE}" \
-				"(&(ObjectClass=${ldap_group_object_class})(cn:dn:=${group}))" \
-				"${ldap_group_owner_attr}" \
-			| grep "${ldap_group_owner_attr}" \
-			| sed "s/${ldap_group_owner_attr}: //" \
-			| sort
-		)
-		if [[ -n "${query_result:-}" ]]; then
-			readarray -t owners <<< "${query_result}"
-		fi
 	fi
 	#
 	# Get data managers for this group.
@@ -376,21 +357,6 @@ for group in "${groups[@]}"; do
 				| tr ',' '\n' \
 				| sort
 		)"
-		if [[ -n "${query_result:-}" ]]; then
-			readarray -t dms <<< "${query_result}"
-		fi
-	else
-		query_result=$(ldapsearch -LLL -o ldif-wrap=no \
-				-H "${LDAP_HOST}" \
-				-D "${LDAP_USER}" \
-				-w "${LDAP_PASS}" \
-				-b "${LDAP_SEARCH_BASE}" \
-				"(&(ObjectClass=${ldap_group_object_class})(cn:dn:=${group}))" \
-				"${ldap_group_datamanager_attr}" \
-			| grep "${ldap_group_datamanager_attr}" \
-			| sed "s/${ldap_group_datamanager_attr}: //" \
-			| sort
-		)
 		if [[ -n "${query_result:-}" ]]; then
 			readarray -t dms <<< "${query_result}"
 		fi
