sjload: partial ShellCheck fixes.

diff --git a/bin/sjload b/bin/sjload
--- a/bin/sjload
+++ b/bin/sjload
@@ -7,9 +7,10 @@
 #
 set -u
 set -e
+set -o pipefail
 umask 0027
-memyselfandi=$(basename $0)
-if [[ "${BASH_VERSINFO}" -lt 4 || "${BASH_VERSINFO[0]}" -lt 4 ]]; then
+memyselfandi=$(basename "${0}")
+if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
   echo "Sorry, you need at least bash 4.x to use ${memyselfandi}." >&2
   exit 1
 fi
@@ -22,7 +23,7 @@ fi
 
 function _Usage() {
     echo
-    echo '${memyselfandi} - SLURM Job Load.'
+    echo "${memyselfandi} - SLURM Job Load."
     echo '        Retrieves the load produced by running jobs and computes job efficiency '
     echo '        by comparing requested resources to actually used resources.'
     echo '        Job stats are retrieved using clustershell (clush) to access nodes '
@@ -50,7 +51,7 @@ USER=''
 JOBS=''
 
 while getopts "u:j:h" opt; do
-  case $opt in
+  case "${opt}" in
     h)
       _Usage
       exit 0
@@ -62,42 +63,42 @@ while getopts "u:j:h" opt; do
       JOBS=${OPTARG}
       ;;
     \?)
-      reportError ${LINENO} '1' "Invalid option -${OPTARG}. Try \"$(basename $0) -h\" for help."
+      echo "FATAL: Invalid option -${OPTARG}. Try '${memyselfandi} -h' for help."
+      exit 1
       ;;
     :)
-      reportError ${LINENO} '1' "Option -${OPTARG} requires an argument. Try \"$(basename $0) -h\" for help."
+      echo "FATAL: Option -${OPTARG} requires an argument. Try '${memyselfandi} -h' for help."
+      exit 1
+      ;;
+    *)
+      echo "FATAL: Unhandled option. Try '${memyselfandi} -h' for help."
+      exit 1
       ;;
   esac
 done
 
 #
-# Make sure there are no extra arguments we did not expect nor need.
-#
-shift $(($OPTIND - 1))
-if [ ! -z ${1:-} ]; then
-  reportError ${LINENO} '1' "Invalid argument \"$1\". Try \"$(basename $0) -h\" for help."
-fi
-
-#
 # Compile list of jobs.
 #
 declare -a JOB_IDS=()
-if [ ! -z "${USER:-}" ]; then
+if [[ -n "${USER:-}" ]]; then
     #
     # Get list of all jobs for this user.
     #
-    JOB_IDS=$(squeue -h --state='R' -o %A -u ${USER} | grep -v CLUSTER)
-elif [ "${JOBS:-}" == 'ALL' ]; then
+    squeue_result="$(squeue -h --state='R' -o %A -u "${USER}" | grep -v CLUSTER | sort)"
+    readarray -t JOB_IDS <<< "${squeue_result}"
+elif [[ "${JOBS:-}" == 'ALL' ]]; then
     #
     # Get list of all jobs.
     #
-    JOB_IDS=$(squeue -h --state='R' -o %A | grep -v CLUSTER)
+    squeue_result="$(squeue -h --state='R' -o %A | grep -v CLUSTER | sort)"
+    readarray -t JOB_IDS <<< "${squeue_result}"
 elif [[ "${JOBS:-}" =~ ',' ]]; then
-    JOB_IDS=$(echo "${JOBS}" | tr ',' ' ')
-elif [[ "${JOBS:-}" =~ '^([0-9]*)-([0-9]*)$' ]]; then
-    JOB_IDS={${BASH_REMATCH[1]}..${BASH_REMATCH[2]}}
-elif [[ "${JOBS:-}" =~ '^([0-9]*)$' ]]; then
-    JOB_IDS=(${JOBS})
+    readarray -t JOB_IDS <<< "${JOBS//,/\n}"
+elif [[ "${JOBS:-}" =~ ^([0-9]*)-([0-9]*)$ ]]; then
+    JOB_IDS=({${BASH_REMATCH[1]}..${BASH_REMATCH[2]}})
+elif [[ "${JOBS:-}" =~ ^([0-9]*)$ ]]; then
+    JOB_IDS=("${JOBS}")
 else
     _Usage
     exit 1
@@ -106,22 +107,21 @@ fi
 #
 # Display header.
 #
-format='%s  %s  %s  %s\n'
-printf "${format}" 'JobID' 'User' 'Efficiency' '%CPU Req.'
+printf '%s  %s  %s  %s\n' 'JobID' 'User' 'Efficiency' '%CPU Req.'
 
-for JOB_ID in ${JOB_IDS[@]}; do
+for JOB_ID in "${JOB_IDS[@]}"; do
     #
     # Default format: "%.18i %.9P %.8j %.8u %.2t %.10M %.6D %R"
     # Specify explicit format without number to make field as long as necessary to capture complete data.
     #
-    job_info=$(squeue -h --job=${JOB_ID} --state='R'  --format='%i %P %j %u %t %M %D %R %C'  2>/dev/null | grep -v CLUSTER)
+    job_info=$(squeue -h --job="${JOB_ID}" --state='R'  --format='%i %P %j %u %t %M %D %R %C'  2>/dev/null | grep -v CLUSTER)
     
     #
     # Check if we found the job.
     #
-    if [ "${job_info}" == '' ]; then
-        if [ "${JOBS:-}" != 'ALL' ]; then
-            echo "FATAL: Invalid job ID (${JOB_ID})"
+    if [[ "${job_info}" == '' ]]; then
+        if [[ "${JOBS:-}" != 'ALL' ]]; then
+            echo "FATAL: Invalid job ID ${JOB_ID}."
         else
             continue
         fi
@@ -130,10 +130,10 @@ for JOB_ID in ${JOB_IDS[@]}; do
     #
     # Parse job details from squeue.
     #
-    user=`echo ${job_info} | awk '{ print $4 }'`
-    node_list=`echo ${job_info} | awk '{ print $8 }'`
-    cores=`echo ${job_info} | awk '{ print $9 }'`
-    node_list=`nodeset -e ${node_list} | tr ' ' ','`
+    user=$(echo "${job_info}" | awk '{print $4}')
+    node_list=$(echo "${job_info}" | awk '{print $8}')
+    cores=$(echo "${job_info}" | awk '{print $9}')
+    node_list=$(nodeset -e "${node_list}" | tr ' ' ',')
     echo "DEBUG: user ${user} | node_list ${node_list} | cores ${cores}"
     
     #
